### ISSUE TITLE
Some InChIKeys give errors

### ISSUE THREAD

**Issue by stanstrup** [wilsontom/classyfireR#1]
Examples:

```r
bad_key <- 
c("WCYWZMWISLQXQU-UHFFFAOYSA-N",
"WCYWZMWISLQXQU-UHFFFAOYSA-N",
"AKGGYBADQZYZPD-UHFFFAOYSA-N",
"MDHYEMXUFSJLGV-UHFFFAOYSA-N")

```

**Comment by wilsontom** [comment]
current version (master branch) now catches missing fields and inserts NA's where appropriate. This should any errors and also make the output a bit more table friendly (see example in README)
